###
POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"JoeBiden",
    "password":"biden@123"
}

###

GET http://localhost:3000/user/tweets/
Content-Type: application/json

{
    "username":"JoeBiden"
}

###

POST http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjk1ODEwMjU3fQ.Z8IblXt-HEjhuIgUcDQx-k4IZfCk7J6Ij0r1TkQrLK0
Content-Type: application/json

{
    "tweet" : "Good Morning..."
}


###
post http://localhost:3000/login/
Content-Type: application/json

{
    "username":"Maneesh123",
    "password":"Maneesh@123"
}
###
get http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hbmVlc2gxMjMiLCJpYXQiOjE2OTU4MDk1MjF9.I6Dc_fZXKmFWjVZ3d6Gc_ivzXWWz7KtqAQOCwMUufGQ
